 version: 2
 jobs:
    first-job:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
   second-job:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A second hello, a more pleasant one"
       - run: sleep 15
  workflows:
   version: 2
   one_and_two:
     jobs:
       - first-job
       - second-job
